### ISSUE TITLE
可以跟安卓的抢红包工具似的，增加一些配置

### ISSUE THREAD

**Issue by Cat7373** [AsTryE/QQRedPackHelper#10]
如：

1. 随机延迟抢红包，等个一两秒再抢
2. 过滤某些关键字，如`测试`、`飞机`、`外挂`等
3. 设置某些群不抢
4. 口令红包这种可以加个单独的开关设置是否抢(如果可以不回复就抢可以无视这个)

**Comment by AsTryE** [comment]
基本功能都加上了 @Cat7373

**Comment by Cat7373** [comment]
群感觉应该默认开启抢红包呀😂
以及只能在消息列表里修改是否开启，在联系人列表里没法修改，不大方便批量修改呀😂

**Comment by Cat7373** [comment]
就是说，不抢某个群应该是黑名单模式呀😂

**Comment by AsTryE** [comment]
更新下，已经改为默认开启了，新增了个人红包设置抢开关。

**Comment by AsTryE** [comment]
批量修改后续可以优化下，像删除清空消息列表什么的。
