### ISSUE TITLE
通过 SignatureInstall.sh 安装的建议

### ISSUE THREAD

**Issue by Cat7373** [AsTryE/QQRedPackHelper#13]
目前安装后会插入这样的代码：
```sh
alias qq='sh /Applications/QQ.app/Contents/MacOS/injectionQQ.sh'
```
建议改成这样：
```sh
alias qq='nohup sh /Applications/QQ.app/Contents/MacOS/injectionQQ.sh > /dev/null 2>&1 &'
```
不然用户在使用`QQ`的过程中必须一直开着终端，感觉很不爽😂

**Comment by AsTryE** [comment]
很棒，可以。下次更新时候再添加上去。

**Comment by Cat7373** [comment]
另，https://github.com/Sunnyyoung/QQTweak-macOS 这个插件似乎安装也是直接替换文件，但不会造成聊天记录、表情等的丢失，使用也是直接点图标开启 QQ 即可，建议可以参考下安装原理

**Comment by TozyZuo** [comment]
我修改了一些代码，可以直接生成QQ.app，替换原生QQ.app。也修复了document的问题
https://github.com/TozyZuo/QQPluginWrapper

**Comment by OiCkilL** [comment]
@TozyZuo 你这个项目最终用户怎么使用的？没看懂

**Comment by TozyZuo** [comment]
@OiCkilL 更新了，并上传了app

**Comment by Cat7373** [comment]
@TozyZuo emmm你这个好像是要用户安装`XCode`？

**Comment by TozyZuo** [comment]
@Cat7373 请看release

**Comment by OiCkilL** [comment]
@TozyZuo 自己编译不成功，提示少文件。你编译好的版本文件比官方大好多哦

**Comment by zhangkun0625** [comment]
自己编译,提示缺少文件substrate.h 然后我自己建了一个项目,把代码复制过去,编译成功,(本来想把编译出来的动态库用optool注入,结果一直闪退,)之前放进去的那个qq.app实际上已经注入了动态库了,双击打开就能看到效果,拖到应用程序替换-ok!
每次打开qq就好了,不用终端启动

**Comment by TKkk-iOSer** [comment]
@AsTryE  建议 hook 下 `NSSearchPathForDirectoriesInDomains` 与 `NSHomeDirectory`，这样就能解决聊天记录、表情消失以及第一次安装插件后首次登陆要求重新输入密码的问题。 可以使用 [fishhook](https://github.com/facebook/fishhook) 去 hook C语言的函数。

**Comment by AsTryE** [comment]
@TKkk-iOSer 感谢提示，修复了聊天记录历史记录问题，并参考了你的QQ助手插件，增加了自动回复消息功能，感谢提供核心代码！

**Comment by TKkk-iOSer** [comment]
@AsTryE nice！
