### ISSUE TITLE
消息列表无法正常显示

### ISSUE THREAD

**Issue by polichan** [AsTryE/QQRedPackHelper#2]
标题

**Comment by AsTryE** [comment]
我这里显示是正常的，你那具体是怎么个不正常情况。

**Comment by xieao100** [comment]
我这里也是，消息列表不显示最新的一条的聊天记录，只显示聊天对象的名字。

**Comment by qinyang1018** [comment]
我的也是， 就是消息列表不显示最后一条消息
![image](https://user-images.githubusercontent.com/15726024/36839163-2b54e3e6-1d7c-11e8-87e2-dd165710180d.png)

**Comment by AsTryE** [comment]
bug已经修复了
