### ISSUE TITLE
最新的6.5.0版本失效

### ISSUE THREAD

**Issue by ginger1995** [AsTryE/QQRedPackHelper#21]
希望能够更新多谢！！

**Comment by Marcello168** [comment]
最新的6.5.0版本失效

**Comment by tipshot** [comment]
6.5.2依然失效

**Comment by tipshot** [comment]
就算重新安装之前的版本也不可以使用。

**Comment by AsTryE** [comment]
试了下，我这里可以抢也，`Mac`系统： `10.13.6` ，`QQ`版本：` 6.5.2（35198）`

**Comment by KocoClass** [comment]
mac10.14  QQ 6.5.2 正常

**Comment by AsTryE** [comment]
2019年02月26日10:57:24   测试 6.5.2 抢红包正常。修复了内存过高问题。
