### ISSUE TITLE
mac10.15，qq6.5.7闪退

### ISSUE THREAD

**Issue by czl0325** [AsTryE/QQRedPackHelper#31]
打开QQ后，点击上面菜单栏的QQ助手->红包设置选项，闪退

测试环境：
mac10.15
qq 6.5.7

**Comment by hyperdai** [comment]
mac10.14.6
qq 6.5.7
出现如题问题。

**Comment by martint028** [comment]
估计不更新了

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by chxbca** [comment]
楼上的兄弟是用了cleanmymac清理了QQ缓存吗？亲测用cmm清理QQ缓存后会出现闪退

**Comment by czl0325** [comment]
cleanmymac这个是收费的，从来不用

**Comment by AsTryE** [comment]
@czl0325 @martint028 @chxbca @hyperdai 已经修复了崩溃问题，测试看看！
