### ISSUE TITLE
感谢大神！终于找到了mac上qq红包神器！顺便提三个小建议！

### ISSUE THREAD

**Issue by xieao100** [AsTryE/QQRedPackHelper#4]
1、qq消息列表不显示最近的聊天记录，只显示聊天对象的名字。
2、能否记住抢红包选项，默认打开qq就已经打开抢红包功能。
3、增加一个防止撤回消息的功能，github里面有，但是没有人把抢红包和防止撤回结合起来使用。
给个链接您可以参考一下。
https://github.com/smartdone/macRevoke
谢谢了！期待您的下次更新！

**Comment by xieao100** [comment]
第一条 图片上传不了，大神可以看看你自己的readme里面的图片，聊天框里面有红包消息，但是左侧最近消息框所有的联系人下面都是空的消息。就是这个问题。

**Comment by AsTryE** [comment]
大概修复了下bug

**Comment by AsTryE** [comment]
@xieao100

**Comment by xieao100** [comment]
@AsTryE 太感谢啦！这下完美了！昨天做梦插件更新了，今天看了看还真更新了。。。😆

**Comment by xieao100** [comment]
@AsTryE 现在的版本抢红包不如上一个版本啊，上一个版本可以后台抢，新版本必须在前台才可以抢红包，而且抢不了口令红包了。还有个问题就是自己发红包也提示抢到红包了。

**Comment by SunboyGo** [comment]
提一个小小的问题，安装了插件后，之前的QQ聊天记录没了。
然后恢复聊天记录的方法就是：下载最新官方QQ安装替换掉就可以了。

**Comment by AsTryE** [comment]
如果之前记录没有，可以采用第二种注入方式QQ，应该就可以看到记录了，用法看说明。
