### ISSUE TITLE
V6.3.1版本 安装无效

### ISSUE THREAD

**Issue by LixinQian** [AsTryE/QQRedPackHelper#6]

**Comment by AsTryE** [comment]
哪里有6.3.1的版本？

**Comment by LixinQian** [comment]
App Store里面的QQ
![2018-03-08 4 19 24](https://user-images.githubusercontent.com/14228362/37140391-8b13ee2e-22ec-11e8-9bf0-c0f5da534b1d.png)

**Comment by AsTryE** [comment]
可以直接去QQ Mac 官网 https://im.qq.com/macqq/ 下载
